export const GRAPE_VARIETIES = [
  "Albarino",
  "Barbera",
  "Cabernet Franc",
  "Cabernet Sauvignon",
  "Carmenere",
  "Carignan",
  "Carménère",
  "Chardonnay",
  "Chenin Blanc",
  "Cinsault",
  "Corvina",
  "Cortese",
  "Dolcetto",
  "Fiano",
  "Furmint",
  "Gamay",
  "Garganega",
  "Gewurztraminer",
  "Godello",
  "Grenache",
  "Gruner Veltliner",
  "Malbec",
  "Marsanne",
  "Merlot",
  "Mourvedre",
  "Muscadet",
  "Muscat",
  "Nebbiolo",
  "Negroamaro",
  "Nero d'Avola",
  "Palomino",
  "Petite Sirah",
  "Petit Verdot",
  "Pinot Blanc",
  "Pinot Grigio",
  "Pinot Gris",
  "Pinot Noir",
  "Pinotage",
  "Primitivo",
  "Riesling",
  "Roussanne",
  "Sangiovese",
  "Sauvignon Blanc",
  "Semillon",
  "Syrah",
  "Shiraz",
  "Tempranillo",
  "Torrontes",
  "Trebbiano",
  "Verdejo",
  "Verdicchio",
  "Vermentino",
  "Viognier",
  "Xinomavro",
  "Zinfandel",
];

export const WINE_COUNTRIES = [
  "Argentina",
  "Australia",
  "Austria",
  "Chile",
  "England",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Italy",
  "New Zealand",
  "Portugal",
  "South Africa",
  "Spain",
  "Sweden",
  "USA",
];

export const WINE_REGIONS = [
  "Alsace",
  "Barbaresco",
  "Barolo",
  "Beaujolais",
  "Bolgheri",
  "Bordeaux",
  "Bourgogne",
  "Brunello di Montalcino",
  "Calistoga",
  "Castilla y Leon",
  "Cava",
  "Central Coast",
  "Central Valley",
  "Champagne",
  "Chablis",
  "Chateauneuf-du-Pape",
  "Chianti",
  "Chianti Classico",
  "Colchagua Valley",
  "Coonawarra",
  "Cotes du Rhone",
  "Douro",
  "Etna",
  "Finger Lakes",
  "Fleurie",
  "Franciacorta",
  "Graves",
  "Haut-Medoc",
  "Hawke's Bay",
  "Jerez",
  "Lake County",
  "Loire",
  "Marlborough",
  "Margaret River",
  "Margaux",
  "McLaren Vale",
  "Medoc",
  "Mendoza",
  "Mosel",
  "Napa Valley",
  "North Coast",
  "Oakville",
  "Pauillac",
  "Pessac-Leognan",
  "Piemonte",
  "Pomerol",
  "Pouilly-Fume",
  "Priorat",
  "Rias Baixas",
  "Ribera del Duero",
  "Rioja",
  "Rutherford",
  "Saint-Emilion",
  "Sancerre",
  "Sauternes",
  "Sonoma",
  "Stellenbosch",
  "Toscana",
  "Trentino-Alto Adige",
  "Valpolicella",
  "Veneto",
  "Western Cape",
  "Willamette Valley",
];
