/** Wine display, tags, food pairing, vintage picker, and footer styles. */
export const wineDisplayStyles = {
  wineCard: {
    borderTopWidth: 1,
    borderTopColor: "#ead8ca",
    paddingTop: 16,
    gap: 12,
  },
  wineCardHighlighted: {
    backgroundColor: "#fff3e0",
    borderRadius: 16,
    padding: 12,
    borderWidth: 2,
    borderColor: "#f4c38c",
  },
  wineImage: {
    width: "100%" as const,
    height: 200,
    borderRadius: 20,
    backgroundColor: "#ead8ca",
  },
  wineCardHeader: {
    flexDirection: "row" as const,
    gap: 12,
  },
  wineType: {
    color: "#6f1d1b",
    fontSize: 11,
    fontWeight: "700" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 1.2,
  },
  wineName: {
    color: "#231815",
    fontSize: 24,
    fontWeight: "700" as const,
    marginTop: 2,
  },
  wineMeta: {
    color: "#564a40",
    marginTop: 4,
  },
  locationText: {
    color: "#6f1d1b",
    marginTop: 6,
    fontWeight: "600" as const,
  },
  quantityBadge: {
    backgroundColor: "#ead8ca",
    alignSelf: "flex-start" as const,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  ratingBadge: {
    alignSelf: "flex-start" as const,
  },
  ratingBadgeText: {
    fontSize: 18,
    color: "#f4c38c",
    letterSpacing: 2,
  },
  quantityBadgeText: {
    color: "#6f1d1b",
    fontWeight: "700" as const,
  },
  tagRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  foodSection: {
    gap: 8,
  },
  tagPill: {
    backgroundColor: "#ead8ca",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: {
    color: "#6f1d1b",
    fontWeight: "700" as const,
    fontSize: 12,
  },
  foodPill: {
    backgroundColor: "#f4c38c",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  foodPillActive: {
    backgroundColor: "#6f1d1b",
  },
  foodText: {
    color: "#5c1d1b",
    fontWeight: "700" as const,
    fontSize: 12,
  },
  foodTextActive: {
    color: "#fffaf5",
  },
  foodCategoryGroup: {
    gap: 6,
  },
  foodCategoryLabel: {
    color: "#564a40",
    fontSize: 11,
    fontWeight: "700" as const,
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  mealSelectedLabel: {
    color: "#6f1d1b",
    fontWeight: "700" as const,
    fontSize: 14,
    backgroundColor: "#f4c38c",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    overflow: "hidden" as const,
  },
  suggestionPill: {
    backgroundColor: "#fffaf5",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#e6d7c8",
  },
  suggestionPillActive: {
    backgroundColor: "#6f1d1b",
    borderColor: "#6f1d1b",
  },
  suggestionText: {
    color: "#6f1d1b",
    fontWeight: "700" as const,
    fontSize: 12,
  },
  suggestionTextActive: {
    color: "#fffaf5",
  },
  notesText: {
    color: "#564a40",
    lineHeight: 21,
  },
  actionRow: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
  },
  dangerText: {
    color: "#9c3d31",
    fontWeight: "700" as const,
  },
  emptyStateCard: {
    alignItems: "center" as const,
    padding: 28,
    gap: 10,
  },
  emptyStateTitle: {
    color: "#2b1714",
    fontSize: 18,
    fontWeight: "700" as const,
  },
  emptyState: {
    color: "#564a40",
    lineHeight: 21,
    textAlign: "center" as const,
  },
  loadingInline: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
  },
  storageSpaceForm: {
    backgroundColor: "#fffaf5",
    borderRadius: 18,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: "#ead8ca",
  },
  vintagePickerOverlay: {
    flex: 1,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  vintagePickerCard: {
    backgroundColor: "#fffaf5",
    borderRadius: 18,
    padding: 20,
    width: "85%" as const,
    maxWidth: 400,
    maxHeight: "60%" as const,
  },
  vintagePickerTitle: {
    fontSize: 18,
    fontWeight: "600" as const,
    color: "#231815",
    marginBottom: 12,
  },
  vintagePickerSubtitle: {
    fontSize: 14,
    color: "#564a40",
    marginBottom: 16,
  },
  vintagePickerItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e6d7c8",
    minHeight: 48,
    justifyContent: "center" as const,
  },
  vintagePickerItemText: {
    fontSize: 16,
    color: "#231815",
  },
  vintagePickerAddButton: {
    marginTop: 12,
    paddingVertical: 14,
    alignItems: "center" as const,
    backgroundColor: "#ead8ca",
    borderRadius: 12,
    minHeight: 48,
    justifyContent: "center" as const,
  },
  vintagePickerAddText: {
    fontSize: 16,
    color: "#6f1d1b",
    fontWeight: "600" as const,
  },
  footerRow: {
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    gap: 8,
    paddingBottom: 8,
  },
  footerVersion: {
    color: "#8f8178",
    fontSize: 10,
    opacity: 0.6,
  },
  footerLink: {
    color: "#8f8178",
    fontSize: 10,
    textDecorationLine: "underline" as const,
  },
} as const;
