import { Platform, StyleSheet } from "react-native";

const serifFont = Platform.select({
  web: '"Cormorant Garamond", "Georgia", serif',
  ios: "Georgia",
  default: "serif",
});

const handFont = Platform.select({
  web: '"Caveat", cursive',
  ios: "Noteworthy-Bold",
  default: "serif",
});

// Haggan-inspired natural wine palette
const c = {
  bg: "#FDFAF6",
  surface: "#FFFFFF",
  surfaceAlt: "#F0EBE3",
  accent: "#C83C2D",
  accentDark: "#A62E22",
  warm: "#E8A87C",
  text: "#2A2A2A",
  textSecondary: "#6B6B6B",
  textLight: "#FDFAF6",
  border: "#E0D8CE",
  borderLight: "#F0EBE3",
  black: "#1A1A1A",
  logoPanel: "#2b1714",
};

export { c as colors, handFont };

export const styles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: c.bg,
  },
  screenCentered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.bg,
    gap: 12,
  },
  scannerScreen: {
    flex: 1,
    backgroundColor: c.bg,
    padding: 18,
    gap: 18,
  },
  catalogEditorContent: {
    gap: 14,
    paddingBottom: 24,
  },
  scannerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  scannerTitle: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 28,
    lineHeight: 30,
    fontWeight: "700",
  },
  scannerFrame: {
    overflow: "hidden",
    borderRadius: 28,
    backgroundColor: c.black,
    minHeight: 420,
  },
  camera: {
    flex: 1,
    minHeight: 420,
  },
  scannerHint: {
    color: c.textSecondary,
    fontSize: 15,
    lineHeight: 22,
  },
  modalActionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  scrollContent: {
    padding: 20,
    gap: 22,
    maxWidth: 560,
    width: "100%",
    alignSelf: "center",
  },
  heroPanel: {
    backgroundColor: c.surface,
    borderRadius: 28,
    padding: 22,
    gap: 12,
    borderWidth: 1.5,
    borderColor: c.accent,
  },
  eyebrow: {
    color: c.accent,
    letterSpacing: 2,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  heroTitle: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 34,
    lineHeight: 36,
    fontWeight: "700",
  },
  heroText: {
    color: c.textSecondary,
    fontSize: 15,
    lineHeight: 23,
  },
  mono: {
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    color: c.text,
  },
  infoBox: {
    marginTop: 6,
    padding: 14,
    borderRadius: 18,
    backgroundColor: c.surfaceAlt,
    gap: 6,
  },
  infoLabel: {
    color: c.accent,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  infoValue: {
    color: c.text,
    fontSize: 14,
  },
  loadingText: {
    color: c.text,
    fontSize: 16,
  },
  panel: {
    backgroundColor: c.surface,
    borderRadius: 24,
    padding: 20,
    gap: 16,
    borderWidth: 1.5,
    borderColor: c.border,
    ...Platform.select({
      web: { boxShadow: "2px 3px 0px rgba(200, 60, 45, 0.08)" },
      default: {},
    }),
  },
  segment: {
    flexDirection: "row",
    backgroundColor: c.surfaceAlt,
    borderRadius: 999,
    padding: 4,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 999,
    alignItems: "center",
  },
  segmentButtonActive: {
    backgroundColor: c.accent,
  },
  segmentText: {
    color: c.textSecondary,
    fontWeight: "700",
  },
  segmentTextActive: {
    color: c.textLight,
  },
  scrollFlex: {
    flex: 1,
  },
  bottomTabBar: {
    flexDirection: "row",
    backgroundColor: c.surface,
    borderTopWidth: 1,
    borderTopColor: c.border,
    paddingBottom: Platform.OS === "ios" ? 20 : 8,
    paddingTop: 8,
  },
  bottomTab: {
    flex: 1,
    alignItems: "center",
    gap: 2,
    minHeight: 44,
    justifyContent: "center",
  },
  bottomTabIcon: {
    fontSize: 20,
    color: c.textSecondary,
  },
  bottomTabIconActive: {
    color: c.accent,
  },
  bottomTabLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: c.textSecondary,
  },
  bottomTabLabelActive: {
    color: c.accent,
  },
  statsSummaryBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: c.surfaceAlt,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  statsSummaryText: {
    color: c.accent,
    fontWeight: "600",
    fontSize: 14,
  },
  statsSummaryToggle: {
    color: c.accent,
    fontSize: 12,
  },
  statsGrid: {
    gap: 8,
  },
  statsGridRow: {
    flexDirection: "row",
    gap: 8,
  },
  storageCard: {
    backgroundColor: c.surfaceAlt,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  storageCardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  storageCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inputGroup: {
    gap: 6,
  },
  inputLabel: {
    color: c.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  input: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
    backgroundColor: c.surface,
    color: c.text,
    fontSize: 15,
    borderWidth: 1,
    borderColor: c.border,
  },
  autocompleteList: {
    marginTop: 6,
    borderRadius: 16,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    overflow: "hidden",
  },
  autocompleteItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: c.borderLight,
  },
  autocompleteText: {
    color: c.text,
    fontSize: 15,
  },
  textarea: {
    minHeight: 96,
    textAlignVertical: "top",
  },
  primaryButton: {
    backgroundColor: c.accent,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 15,
  },
  imageButtonRow: {
    flexDirection: "row",
    gap: 8,
  },
  secondaryButton: {
    backgroundColor: "transparent",
    borderRadius: 999,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    flex: 1,
    borderWidth: 1.5,
    borderColor: c.border,
  },
  secondaryButtonText: {
    color: c.text,
    fontWeight: "700",
  },
  authNotice: {
    color: c.accent,
    lineHeight: 21,
  },
  authFootnote: {
    color: c.textSecondary,
    lineHeight: 21,
    fontSize: 13,
  },
  inlineLinkButton: {
    alignSelf: "flex-start",
  },
  panelHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  panelTitle: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 24,
    fontWeight: "700",
  },
  linkText: {
    color: c.accent,
    fontWeight: "700",
  },
  metricsRow: {
    flexDirection: "row",
    gap: 10,
  },
  metricCard: {
    flex: 1,
    backgroundColor: c.surfaceAlt,
    borderRadius: 18,
    padding: 12,
    gap: 4,
  },
  metricValue: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 22,
    fontWeight: "700",
  },
  metricLabel: {
    color: c.textSecondary,
    fontSize: 12,
  },
  insightCard: {
    borderRadius: 18,
    backgroundColor: c.surface,
    padding: 14,
    gap: 6,
    borderWidth: 1,
    borderColor: c.border,
  },
  importSuggestionCard: {
    borderRadius: 18,
    backgroundColor: "#FFF8F0",
    padding: 14,
    gap: 8,
    borderWidth: 1,
    borderColor: c.warm,
  },
  importModeRow: {
    gap: 8,
  },
  quickImportButton: {
    backgroundColor: c.surface,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: c.border,
  },
  quickImportButtonActive: {
    backgroundColor: c.accent,
    borderColor: c.accent,
  },
  quickImportText: {
    color: c.accent,
    fontWeight: "700",
    textAlign: "center",
  },
  quickImportTextActive: {
    color: "#FFFFFF",
  },
  importOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: c.surface,
  },
  importOptionRowActive: {
    backgroundColor: c.surfaceAlt,
    borderWidth: 1,
    borderColor: c.accent,
  },
  importOptionText: {
    color: c.text,
    fontWeight: "600",
  },
  importOptionState: {
    color: c.textSecondary,
    fontWeight: "700",
  },
  importOptionTextActive: {
    color: c.accent,
  },
  insightValue: {
    color: c.text,
    fontSize: 18,
    fontWeight: "700",
  },
  recommendationCard: {
    borderRadius: 18,
    backgroundColor: c.surface,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: c.border,
  },
  storageSpaceCard: {
    borderRadius: 18,
    backgroundColor: c.surface,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: c.border,
  },
  recommendationHeader: {
    flexDirection: "row",
    gap: 12,
  },
  storageSpaceHeader: {
    flexDirection: "row",
    gap: 12,
  },
  recommendationName: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 20,
    fontWeight: "700",
    marginTop: 2,
  },
  doubleRow: {
    flexDirection: "row",
    gap: 12,
  },
  wineCard: {
    borderTopWidth: 1,
    borderTopColor: c.border,
    paddingTop: 16,
    gap: 12,
  },
  wineCardHighlighted: {
    backgroundColor: "#FFF8F0",
    borderRadius: 16,
    padding: 12,
    borderWidth: 2,
    borderColor: c.warm,
  },
  wineImage: {
    width: "100%",
    height: 200,
    borderRadius: 20,
    backgroundColor: c.surfaceAlt,
  },
  wineCardHeader: {
    flexDirection: "row",
    gap: 12,
  },
  wineType: {
    color: c.accent,
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  wineName: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 24,
    fontWeight: "700",
    marginTop: 2,
  },
  wineMeta: {
    color: c.textSecondary,
    marginTop: 4,
  },
  locationText: {
    color: c.accent,
    marginTop: 6,
    fontWeight: "600",
  },
  quantityBadge: {
    backgroundColor: c.surfaceAlt,
    alignSelf: "flex-start",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  ratingBadge: {
    alignSelf: "flex-start",
  },
  ratingBadgeText: {
    fontSize: 18,
    color: c.warm,
    letterSpacing: 2,
  },
  quantityBadgeText: {
    color: c.accent,
    fontWeight: "700",
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  foodSection: {
    gap: 8,
  },
  tagPill: {
    backgroundColor: c.surfaceAlt,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tagText: {
    color: c.text,
    fontWeight: "700",
    fontSize: 12,
  },
  foodPill: {
    backgroundColor: c.surfaceAlt,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  foodPillActive: {
    backgroundColor: c.accent,
  },
  foodText: {
    color: c.text,
    fontWeight: "700",
    fontSize: 12,
  },
  foodTextActive: {
    color: "#FFFFFF",
  },
  foodPairingRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 6,
    flexWrap: "wrap",
  },
  foodPairingLabel: {
    color: c.textSecondary,
    fontSize: 12,
    fontWeight: "500",
  },
  foodPairingTags: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
    flexWrap: "wrap",
  },
  foodPairingText: {
    color: c.textSecondary,
    fontSize: 12,
    fontWeight: "500",
    backgroundColor: c.surfaceAlt,
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    overflow: "hidden",
  },
  foodPairingOverflow: {
    color: c.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    paddingHorizontal: 4,
  },
  foodCategoryGroup: {
    gap: 6,
  },
  foodCategoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
    paddingHorizontal: 2,
  },
  foodCategoryLabel: {
    color: c.textSecondary,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  foodCategoryLabelActive: {
    color: c.accent,
  },
  foodCategoryChevron: {
    color: c.textSecondary,
    fontSize: 14,
  },
  mealSelectedLabel: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
    backgroundColor: c.accent,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    overflow: "hidden",
  },
  suggestionPill: {
    backgroundColor: c.surfaceAlt,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  suggestionPillActive: {
    backgroundColor: c.accent,
  },
  suggestionText: {
    color: c.text,
    fontWeight: "700",
    fontSize: 12,
  },
  suggestionTextActive: {
    color: "#FFFFFF",
  },
  notesText: {
    color: c.textSecondary,
    lineHeight: 21,
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: c.border,
  },
  drinkAction: {
    backgroundColor: c.accent,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  drinkActionText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 13,
  },
  actionSpacer: {
    flex: 1,
  },
  dangerText: {
    color: "#C85050",
    fontSize: 13,
  },
  filterToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "transparent",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: c.border,
  },
  filterToggleText: {
    color: c.accent,
    fontWeight: "700",
    fontSize: 13,
  },
  emptyStateCard: {
    alignItems: "center" as const,
    padding: 28,
    gap: 10,
  },
  emptyStateTitle: {
    fontFamily: serifFont,
    color: c.text,
    fontSize: 18,
    fontWeight: "700" as const,
  },
  emptyState: {
    color: c.textSecondary,
    lineHeight: 21,
    textAlign: "center" as const,
  },
  loadingInline: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  storageSpaceForm: {
    backgroundColor: c.surface,
    borderRadius: 18,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: c.border,
  },
  vintagePickerOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  vintagePickerCard: {
    backgroundColor: c.surface,
    borderRadius: 18,
    padding: 20,
    width: "85%",
    maxWidth: 400,
    maxHeight: "60%",
    borderWidth: 1,
    borderColor: c.border,
  },
  vintagePickerTitle: {
    fontFamily: serifFont,
    fontSize: 18,
    fontWeight: "600",
    color: c.text,
    marginBottom: 12,
  },
  vintagePickerSubtitle: {
    fontSize: 14,
    color: c.textSecondary,
    marginBottom: 16,
  },
  vintagePickerItem: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: c.border,
    minHeight: 48,
    justifyContent: "center",
  },
  vintagePickerItemText: {
    fontSize: 16,
    color: c.text,
  },
  vintagePickerAddButton: {
    marginTop: 12,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 12,
    minHeight: 48,
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: c.accent,
  },
  vintagePickerAddText: {
    fontSize: 16,
    color: c.accent,
    fontWeight: "600",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    paddingBottom: 8,
  },
  footerVersion: {
    color: c.textSecondary,
    fontSize: 10,
    opacity: 0.6,
  },
  footerLink: {
    color: c.textSecondary,
    fontSize: 10,
    textDecorationLine: "underline",
  },
  statBox: {
    flex: 1,
    backgroundColor: c.surfaceAlt,
    borderRadius: 14,
    padding: 12,
    alignItems: "center",
  },
  statBoxValue: {
    fontFamily: serifFont,
    color: c.accent,
    fontSize: 20,
    fontWeight: "800",
  },
  statBoxLabel: {
    color: c.textSecondary,
    fontSize: 11,
    fontWeight: "600",
  },
  infoBadge: {
    backgroundColor: "transparent",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: c.border,
  },
  infoBadgeText: {
    color: c.accent,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 1,
  },
  wineThumbnail: {
    width: 64,
    height: 86,
    borderRadius: 12,
    backgroundColor: c.surfaceAlt,
  },
  sectionChevron: {
    color: c.textSecondary,
    fontSize: 16,
    fontWeight: "600",
  },
});
