insert into public.product_catalog_entries (
  barcode,
  name,
  producer,
  country,
  region,
  grape,
  type,
  vintage,
  food_pairings,
  source_label,
  source_confidence
)
values
  (
    '5603016003505',
    'Vinhas de Pegoes Syrah',
    'Adega de Pegoes',
    'Portugal',
    'Peninsula de Setubal',
    'Syrah',
    'Rött',
    null,
    array['lamm', 'nöt', 'grillat'],
    'Producer seed',
    'high'
  ),
  (
    '5603016000665',
    'Adega de Pegoes Touriga Nacional',
    'Adega de Pegoes',
    'Portugal',
    'Peninsula de Setubal',
    'Touriga Nacional',
    'Rött',
    null,
    array['lamm', 'vilt', 'grillat'],
    'Producer seed',
    'high'
  ),
  (
    '5603016000788',
    'Adega de Pegoes White',
    'Adega de Pegoes',
    'Portugal',
    'Peninsula de Setubal',
    'Fernao Pires, Moscatel, Arinto',
    'Vitt',
    null,
    array['fisk', 'skaldjur', 'sallad'],
    'Producer seed',
    'high'
  ),
  (
    '810404021538',
    'Niersteiner Riesling Trocken Aus Ersten Lagen',
    'Weingut Wittmann',
    'Germany',
    'Rheinhessen',
    'Riesling',
    'Vitt',
    2024,
    array['fisk', 'asiatiskt', 'skaldjur'],
    'Importer seed',
    'high'
  ),
  (
    '051497037239',
    'Vina Real Gran Reserva',
    'Vina Real',
    'Spain',
    'Rioja',
    'Tempranillo, Graciano',
    'Rött',
    null,
    array['lamm', 'nöt', 'lagrad ost'],
    'Distributor seed',
    'high'
  ),
  (
    '051497037154',
    'Contino Garnacha',
    'Contino',
    'Spain',
    'Rioja',
    'Garnacha',
    'Rött',
    null,
    array['lamm', 'grillat', 'tapas'],
    'Distributor seed',
    'high'
  ),
  (
    '051497053093',
    'Regueiron Godello',
    'Virgen del Galir',
    'Spain',
    'Valdeorras',
    'Godello',
    'Vitt',
    null,
    array['fisk', 'skaldjur', 'sallad'],
    'Distributor seed',
    'high'
  ),
  (
    '00098709088580',
    'Bodega Catena Zapata Malbec',
    'Bodega Catena Zapata',
    'Argentina',
    'Mendoza',
    'Malbec',
    'Rött',
    2016,
    array['nöt', 'grillat', 'vilt'],
    'Retail seed',
    'medium'
  ),
  (
    '00669576019214',
    'Decoy Sauvignon Blanc',
    'Decoy',
    'USA',
    'Napa Valley',
    'Sauvignon Blanc',
    'Vitt',
    2018,
    array['fisk', 'getost', 'sallad'],
    'Retail seed',
    'medium'
  ),
  (
    '8000160623288',
    'Granaio Chianti Classico DOCG',
    'Fattorie Melini',
    'Italy',
    'Chianti Classico',
    'Sangiovese Grosso',
    'Rött',
    null,
    array['pasta', 'pizza', 'lamm'],
    'Retail seed',
    'medium'
  ),
  (
    '4860099003308',
    'Umano Kisi Dry White Wine',
    'Umano Wines',
    'Georgia',
    'Kakheti',
    'Kisi',
    'Vitt',
    2024,
    array['fisk', 'ost', 'sallad'],
    'Retail seed',
    'medium'
  )
on conflict (barcode) do update
set
  name = excluded.name,
  producer = excluded.producer,
  country = excluded.country,
  region = excluded.region,
  grape = excluded.grape,
  type = excluded.type,
  vintage = excluded.vintage,
  food_pairings = excluded.food_pairings,
  source_label = excluded.source_label,
  source_confidence = excluded.source_confidence;
